name: color_learning_app
description: A simple app to teach children about colors.

publish_to: 'none' # This prevents the package from being accidentally published

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/red.mp3
    - assets/audio/green.mp3
    - assets/audio/blue.mp3
    - assets/audio/yellow.mp3
    - assets/audio/orange.mp3
    - assets/audio/purple.mp3
    - assets/audio/pink.mp3
    - assets/audio/brown.mp3
    - assets/audio/black.mp3
    - assets/audio/white.mp3
